reci4slova = open('reci4slova.txt', 'r', encoding="utf-8")
reci5slova = open('reci5slova.txt', 'r', encoding="utf-8")
reci6slova = open('reci6slova.txt', 'r', encoding="utf-8")
reci7slova = open('reci7slova.txt', 'r', encoding="utf-8")
reci8slova = open('reci8slova.txt', 'r', encoding="utf-8")
reci9slova = open('reci9slova.txt', 'r', encoding="utf-8")
reci10slova = open('reci10slova.txt', 'r', encoding="utf-8")
reci11slova = open('reci11slova.txt', 'r', encoding="utf-8")
reci12slova = open('reci12slova.txt', 'r', encoding="utf-8")

sortreci4slova = open('sortreci4slova.txt', 'w', encoding="utf-8")
sortreci5slova = open('sortreci5slova.txt', 'w', encoding="utf-8")
sortreci6slova = open('sortreci6slova.txt', 'w', encoding="utf-8")
sortreci7slova = open('sortreci7slova.txt', 'w', encoding="utf-8")
sortreci8slova = open('sortreci8slova.txt', 'w', encoding="utf-8")
sortreci9slova = open('sortreci9slova.txt', 'w', encoding="utf-8")
sortreci10slova = open('sortreci10slova.txt', 'w', encoding="utf-8")
sortreci11slova = open('sortreci11slova.txt', 'w', encoding="utf-8")
sortreci12slova = open('sortreci12slova.txt', 'w', encoding="utf-8")

lines = sorted(reci4slova.readlines())
sortreci4slova.write(str(' '.join(lines)))
lines = sorted(reci5slova.readlines())
sortreci5slova.write(str(' '.join(lines)))
lines = sorted(reci6slova.readlines())
sortreci6slova.write(str(' '.join(lines)))
lines = sorted(reci7slova.readlines())
sortreci7slova.write(str(' '.join(lines)))
lines = sorted(reci8slova.readlines())
sortreci8slova.write(str(' '.join(lines)))
lines = sorted(reci9slova.readlines())
sortreci9slova.write(str(' '.join(lines)))
lines = sorted(reci10slova.readlines())
sortreci10slova.write(str(' '.join(lines)))
lines = sorted(reci11slova.readlines())
sortreci11slova.write(str(' '.join(lines)))
lines = sorted(reci12slova.readlines())
sortreci12slova.write(str(' '.join(lines)))
